### ISSUE TITLE
Wazuh Docker FAQ typo

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-documentation#1893]
Hi team,

There is a typo in the `How can I store Wazuh data?` section:

```
elasticsearch:
  image: wazuh/wazuh:latest
  hostname: wazuh-manager
  ports:
    - "1514:1514/udp"
    - "1515:1515"
    - "514:514"
    - "55000:55000"
  networks:
    - docker_elk
  volumes:
    - /path/to/storage:/var/ossec/data
```

Should be 

```
wazuh:
  image: wazuh/wazuh:latest
  hostname: wazuh-manager
  ports:
    - "1514:1514/udp"
    - "1515:1515"
    - "514:514"
    - "55000:55000"
  networks:
    - docker_elk
  volumes:
    - /path/to/storage:/var/ossec/data
```
