### ISSUE TITLE
Add Filebeat module extra documentation

### ISSUE THREAD

**Issue by migruiz4** [wazuh/wazuh-documentation#2203]
Hi team,

The filebeat module is missing some configuration details.

I think this section should include two parts:

### Customize configuration
For example, it is possible to configure multiple inputs and different output indices as it follows, as the documentation doesn't reflect any of this:

```yaml
# Wazuh - Filebeat configuration file
filebeat.modules:
#  Normal module, path:  /var/ossec/logs/alerts/alerts.json, index: wazuh-alerts-3.x-yyyy.mm.dd
- module: wazuh
    alerts:
      enabled: true
    archives:
      enabled: false

# Custom input, path: /var/custom/more_alerts/alerts.json, index: wazuh-alerts-custom-yyyy.mm.dd
- module: wazuh
  alerts:
    enabled: true
    input:
      paths:
        - "/var/custom/more_alerts/alerts.json"
      fields:
        index_prefix: "wazuh-alerts-custom-"

setup.template.json.enabled: true
setup.template.json.path: '/etc/filebeat/wazuh-template.json'
setup.template.json.name: 'wazuh'
setup.template.overwrite: true
setup.ilm.enabled: false
output.elasticsearch.hosts: ['http://localhost:9200']
```

Custom inputs will be processed by the Wazuh pipeline as well.

### Customize the pipeline

Telling the users where the Filebeat module pipeline is located, linked to Elasticsearch pipeline documentation so they have a reference and how to apply and check that the changes were properly applied.
