### ISSUE TITLE
Add new auditd fields in FIM alerts (v3.13)

### ISSUE THREAD

**Issue by Lopuiz** [wazuh/wazuh-documentation#2404]
Hello team!

PR number [4782](https://github.com/wazuh/wazuh/pull/4782) adds three new auditd fields in FIM alerts. New alert will be as follow:

```
** Alert 1585556428.15792: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,
2020 Mar 30 10:20:28 lopezziur->syscheck
Rule: 554 (level 5) -> 'File added to the system.'
File '/home/lopezziur/testing1/test' added
Mode: whodata

Attributes:
 - Size: 0
 - Permissions: rw-rw-r--
 - Date: Mon Mar 30 10:20:27 2020
 - Inode: 10786885
 - User: lopezziur (1000)
 - Group: lopezziur (1000)
 - MD5: d41d8cd98f00b204e9800998ecf8427e
 - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
 - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
 - (Audit) User name: lopezziur
 - (Audit) Audit name: lopezziur
 - (Audit) Effective name: lopezziur
 - (Audit) Group name: lopezziur
 - (Audit) Process id: 8772
 - (Audit) Process name: /bin/touch
 - (Audit) Process cwd: /home/lopezziur
 - (Audit) Parent process name: /bin/bash
 - (Audit) Parent process id: 28027
 - (Audit) Parent process cwd: /home/lopezziur
```

I hope this PR will be merged in 3.13, and the documentation must have these fields in v3.13.

Best regards,
Eva
