### ISSUE TITLE
Invalid sample for /usr/share/kibana/optimize/wazuh/config/wazuh.yml

### ISSUE THREAD

**Issue by vsenko** [wazuh/wazuh-documentation#3112]
Looks like https://github.com/wazuh/wazuh-documentation/commit/ab1a34a890c503ae6fa2ec412359a45e8576db8d introduces an erroneous configuration sample:
```yml
hosts:
  - default:
    url: https://localhost
    port: 55000
    username: wazuh-wui
    password: wazuh-wui
```
In this case `url`, `port`, `username` and `password` are sibling of `default`.

Should be:
```yml
hosts:
  - default:
      url: https://localhost
      port: 55000
      username: wazuh-wui
      password: wazuh-wui
```
