### ISSUE TITLE
securityadmin.sh script stuck when using DNS in certificates

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-documentation#3661]
We followed the guide https://documentation.wazuh.com/current/installation-guide/open-distro/distributed-deployment/step-by-step-installation/elasticsearch-cluster/elasticsearch-multi-node-cluster.html with this configuration in 3 elasticsearch nodes:
```
network.host: 172.20.1.127
node.name: node-1
cluster.name: siem
cluster.initial_master_nodes:
        - node-1
        - node-2
        - node-3
discovery.seed_hosts:
        - test-node1.wazuh.info
        - test-node2.wazuh.info
        - test-node3.wazuh.info

node.master: true
node.data: true
node.ingest: true

opendistro_security.ssl.transport.pemcert_filepath: /etc/elasticsearch/certs/elasticsearch.pem
opendistro_security.ssl.transport.pemkey_filepath: /etc/elasticsearch/certs/elasticsearch.key
opendistro_security.ssl.transport.pemtrustedcas_filepath: /etc/elasticsearch/certs/root-ca.pem
opendistro_security.ssl.transport.enforce_hostname_verification: false
opendistro_security.ssl.transport.resolve_hostname: false
opendistro_security.ssl.http.enabled: true
opendistro_security.ssl.http.pemcert_filepath: /etc/elasticsearch/certs/elasticsearch_http.pem
opendistro_security.ssl.http.pemkey_filepath: /etc/elasticsearch/certs/elasticsearch_http.key
opendistro_security.ssl.http.pemtrustedcas_filepath: /etc/elasticsearch/certs/root-ca.pem
opendistro_security.nodes_dn:
- CN=test-node1.wazuh.info,OU=Docu,O=Wazuh,L=California,C=US
- CN=test-node2.wazuh.info,OU=Docu,O=Wazuh,L=California,C=US
- CN=test-node3.wazuh.info,OU=Docu,O=Wazuh,L=California,C=US
opendistro_security.authcz.admin_dn:
- CN=admin,OU=Docu,O=Wazuh,L=California,C=US


opendistro_security.audit.type: internal_elasticsearch
opendistro_security.enable_snapshot_restore_privilege: true
opendistro_security.check_snapshot_restore_write_privileges: true
opendistro_security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]
cluster.routing.allocation.disk.threshold_enabled: false
node.max_local_storage_nodes: 3

path.data: /var/lib/elasticsearch
path.logs: /var/log/elasticsearch
```
Changing the node IP and name in every new node. We used the following file for certificates creation:
```
# Self-signed certificate authority
ca:
   root:
      dn: CN=elasticsearch,OU=Docu,O=Wazuh,L=California,C=US
      keysize: 2048
      validityDays: 3650
      pkPassword: none
      file: root-ca.pem

# Default values and global settings
defaults:
      validityDays: 3650
      pkPassword: none
      generatedPasswordLength: 12
      httpsEnabled: true

# Nodes certificates
nodes:
  - name: node-1
    dn: CN=test-node1.wazuh.info,OU=Docu,O=Wazuh,L=California,C=US
    ip: 
      - 54.173.230.119
  - name: node-2
    dn: CN=test-node2.wazuh.info,OU=Docu,O=Wazuh,L=California,C=US
    ip: 
      - 3.89.150.61
  - name: node-3
    dn: CN=test-node3.wazuh.info,OU=Docu,O=Wazuh,L=California,C=US
    ip:
      - 172.20.1.176
  - name: kibana
    dn: CN=test-kibana.wazuh.info,OU=Docu,O=Wazuh,L=California,C=US 
    ip:
      - 10.116.22.45

# Clients certificates
clients:
  - name: admin
    dn: CN=admin,OU=Docu,O=Wazuh,L=California,C=US
    admin: true
  - name: filebeat-1
    dn: CN=filebeat-1,OU=Docu,O=Wazuh,L=California,C=US
  - name: filebeat-2
    dn: CN=filebeat-2,OU=Docu,O=Wazuh,L=California,C=US     
```
and the security admin process stuck and produce the attached log. 
[log.txt](https://github.com/wazuh/wazuh-documentation/files/6278137/log.txt)

Regards, 
Alberto R
