### ISSUE TITLE
Typo in the migration documentation

### ISSUE THREAD

**Issue by kamilkroliszewski** [wazuh/wazuh-documentation#3855]
There is a typo in migration documentation:
https://github.com/wazuh/wazuh-documentation/blob/4.1/source/docker/upgrade-guide.rst

Right now it is : 
```
volumes:
migration:
  external:
    name: migration
```

And it should be:
```
volumes:
  migration:
    external:
      name: migration
```
