### ISSUE TITLE
[user-manual] wazuh-kubernetes: Improve explanation on how to expose wazuh server API

### ISSUE THREAD

**Issue by nicop311** [wazuh/wazuh-documentation#4656]
Hello, Is it possible to add more information on how to expose Wazuh
server API and services in the context of the Wazuh-kubernetes local
deployment?

I get that this depends on the flavor of the K8s cluster, and it is probably
different on AWS than on a local K8s cluster. But an example would be helpful,
**espacially for the agent-authd feature.**

## Affected documentation sections

I find that the foolowing sections lack information on how to expose
wazuh-server API and ports when it is deployed on Kubernetes.

* Deploying with kubernetes in AWS:
  * Github : https://github.com/wazuh/wazuh-documentation/blob/4.2/source/deploying-with-kubernetes/kubernetes-conf.rst
  * Web :https://documentation.wazuh.com/current/deploying-with-kubernetes/kubernetes-conf.html

* Deployment with kubernetes on local environment:
  * Github :https://github.com/wazuh/wazuh-documentation/blob/4.2/source/deploying-with-kubernetes/kubernetes-local-env.rst
  * Web : https://documentation.wazuh.com/current/deploying-with-kubernetes/kubernetes-local-env.html

* wazuh-kubernetes project: https://github.com/wazuh/wazuh-kubernetes

## My problem and my questions

I am not able to register my Wazuh Agent to my Wazuh server deployed on a local
Kubernetes cluster.

- [**Question:** Can we put an FQDN in the Wazuh agent `ossec.conf` config file?](#question-can-we-put-an-fqdn-in-the-wazuh-agent-ossecconf-config-file)
- [**Question:** What port should I set in the Wazuh agent `ossec.conf` config file?](#question-what-port-should-i-set-in-the-wazuh-agent-ossecconf-config-file)

I follow the Wazuh user-manual. But it lacks information on how to expose
Wazuh services on Kubernetes.

Source: https://documentation.wazuh.com/current/user-manual/registering/index.html

## My goal: use Kubernetes Ingress to expose Wazuh

My goal is to use [K8s ingress](https://kubernetes.io/fr/docs/concepts/services-networking/ingress/)
to expose the wazuh-server deployed with Wazuh-kubernetes on a local
K8s cluster.

## FQDN suggested by the wazuh-kubernetes in AWS

The 3 following Fully qualified domain name (FQDN) are suggested in the
_Wazuh on AWS documentation_ :

* `wazuh-master.your-domain.com`: Wazuh API and authd registration service.
* `wazuh-manager.your-domain.com`: Reporting service.
* `wazuh.your-domain.com`: Kibana and Wazuh app.

I suggest adding a 4th FQDN: **wazuh-api.your-domain.com**.
This one is dedicated to wazuh API. We separate it from the authd registration
service.

## Example of k8s svc for a Wazuh Kubernetes Local Deployment

**Note** This is a Local K8s Deployment, this is not Wazuh on AWS.

```
$ kubectl get svc -n wazuh
```
```
NAME                  TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)                          AGE
elasticsearch         LoadBalancer   10.96.34.141   <pending>     9200:30206/TCP                   10s
kibana                LoadBalancer   10.96.38.21    <pending>     443:32705/TCP                    10s
wazuh                 LoadBalancer   10.96.81.184   <pending>     1515:31074/TCP,55000:31425/TCP   9s
wazuh-cluster         ClusterIP      None           <none>        1516/TCP                         9s
wazuh-elasticsearch   ClusterIP      None           <none>        9300/TCP                         9s
wazuh-workers         LoadBalancer   10.96.73.88    <pending>     1514:30370/TCP                   9s
```

## My suggestion of FQDN to use with K8s Ingress

This table is inspired by what can be found in the [Wazuh on AWS doc](https://documentation.wazuh.com/current/deploying-with-kubernetes/kubernetes-conf.html#pods).

This is the list of default Wazuh server ports to expose:

| K8s svc name  |  port |  Description                          | Route                                       |
|---------------|-------|---------------------------------------|---------------------------------------------|
| kibana        |   443 | kibana and Wazuh Web GUI              | `wazuh.your-domain.com:443`                 |
| wazuh         | 55000 | Wazuh REST API                        | `wazuh-api.your-domain.com:55000`           |
| wazuh         |  1515 | Agent registration service (authd)    | `wazuh-master.your-domain.com:1515`         |
| wazuh-workers |  1514 | Reporting service                     | `wazuh-manager.your-domain.com:1514`        |
| wazuh-cluster |  none | Communication for Wazuh manager nodes.| none ?                                      |

You can see one FQDN for the "Wazuh Agent registration service (authd)" and
one FQDN for "Wazuh REST API". I do that because I need to separate
ports 55000 and 1515 in the Kubernetes Ingress configuration file: I create
one ingress route per port.

## **Question:** Can we put an FQDN in the Wazuh agent `ossec.conf` config file?

I am not sure which one I should put: `wazuh-master.your-domain.com` or
`wazuh-manager.your-domain.com` or something else...

From this [issue 5167](https://github.com/wazuh/wazuh/issues/5167#issuecomment-631536516),
I understand it is possible to use a FQDN in the wazuh agent `ossec.conf` file.

```
cat /var/ossec/etc/ossec.conf
```

```xml
<client>
  <server>
    <address>wazuh-manager.your-domain.com</address>
    ...
  </server>
</client>
```

## Kubernetes Ingress configuration file

YAML manifest for Kubernetes Ingress.

```yaml
---
# Kibana and Wazuh app Web GUI.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wazuh-kibana-ingress
  # namespace: wazuh # namespace omitted
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-passthrough: 'true'
    #nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  tls:
    - hosts:
      # wazuh.your-domain.com: Kibana and Wazuh app Web GUI.
      - wazuh.your-domain.com
  rules:
  - host: "wazuh.your-domain.com"
    http:
      paths:
      # Wazuh Kibana Web UI dashboard
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: kibana
            port:
              number: 443
---
# Wazuh  API
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wazuh-api-ingress
  # namespace: wazuh # namespace omitted
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-passthrough: 'true'
    #nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  tls:
    - hosts:
      # wazuh-api.your-domain.com: Wazuh API
      - wazuh-api.your-domain.com
  rules:
  - host: "wazuh-api.your-domain.com"
    http:
      paths:
      # Wazuh REST API
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: wazuh
            port:
              number: 55000
---
# Wazuh agent authd registration service.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wazuh-agent-authd-ingress
  # namespace: wazuh # namespace omitted
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-passthrough: 'true'
    #nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  tls:
    - hosts:
      # wazuh-master.your-domain.com: Wazuh authd registration service.
      - wazuh-master.your-domain.com
  rules:
  - host: "wazuh-master.your-domain.com"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: wazuh
            port:
              number: 1515
---
# Wazuh Reporting service
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wazuh-reporting-ingress
  # namespace: wazuh # namespace omitted
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-passthrough: 'true'
    #nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  tls:
    - hosts:
      # wazuh-manager.your-domain.com: Reporting service
      - wazuh-manager.your-domain.com
  rules:
  - host: "wazuh-manager.your-domain.com"
    http:
      paths:
      # Wazuh Reporting service
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: wazuh-workers
            port:
              number: 1514
```

Check your kubernetes Ingress object:

```
kubectl get ing -n wazuh
```
```
NAME                        CLASS    HOSTS                                        ADDRESS     PORTS     AGE
wazuh-agent-authd-ingress   <none>   wazuh-master.your-domain.com    localhost   80, 443   2d21h
wazuh-api-ingress           <none>   wazuh-api.your-domain.com       localhost   80, 443   4d2h
wazuh-kibana-ingress        <none>   wazuh.your-domain.com           localhost   80, 443   4d2h
wazuh-reporting-ingress     <none>   wazuh-manager.your-domain.com   localhost   80, 443   4d2h
```

## **Question:** What port should I set in the Wazuh agent `ossec.conf` config file?

What should I put in `client.server.port` and `client.server.protocol`?
If I use the Kubernetes Ingress: I expose with port 80 or 443.

```
cat /var/ossec/etc/ossec.conf
```

```xml
<client>
  <server>
    <address>wazuh-manager.your-domain.com</address>
    <port>443</port>
    <protocol>tcp</protocol>
    ...
  </server>
</client>
```

## Testing Wazuh API requests: **Success**

Thanks to Kubernetes Ingress, we expose `wazuh-api.your-domain.com` on
**port 443**.
We assume you can resolve `wazuh-api.your-domain.com` (with DNS for example).
Below is an example of the request for a TOKEN, with the default passwords from the [Kubernetes secret](https://github.com/wazuh/wazuh-kubernetes/blob/master/wazuh/secrets/wazuh-api-cred-secret.yaml).

```
TOKEN=$(curl -u wazuh-wui:MyS3cr37P450r.*- -k -X GET "https://wazuh-api.your-domain.com/security/user/authenticate?raw=true")
```

This request is working.

## Testing Wazuh agent authd registration service: FAILED

I am **not able** to register my agents on my Wazuh server deployed on
Kubernetes local cluster.

See my questions:
- [**Question:** Can we put an FQDN in the Wazuh agent `ossec.conf` config file?](#question-can-we-put-an-fqdn-in-the-wazuh-agent-ossecconf-config-file)
- [**Question:** What port should I set in the Wazuh agent `ossec.conf` config file?](#question-what-port-should-i-set-in-the-wazuh-agent-ossecconf-config-file)

### trying to register the agent with REST API

From my VM where my Wazuh Agent is installed, I retrieve a JWT with the Wazuh API:

```
TOKEN=$(curl -u wazuh-wui:MyS3cr37P450r.*- -k -X GET "https://wazuh-api.your-domain.com/security/user/authenticate?raw=true")
```

Then I follow [Registering the Wazuh agents using the Wazuh API](https://documentation.wazuh.com/current/user-manual/registering/restful-api-registration.html):

```
curl -k -X POST -d '{"name":"monitoring-target","ip":"10.10.10.10"}' "https://wazuh-api.your-domain.com/agents?pretty=true" -H "Content-Type:application/json" -H "Authorization: Bearer $TOKEN"
```

```
{
   "data": {
      "id": "004",
      "key": "MDA0I...TRUNCATED_KEY...RiNzI="
   },
   "error": 0
}
```

With the Wazuh Agent CLI, I add the Registering key: 

```
# /var/ossec/bin/manage_agents -i <key from previous step>
sudo su /var/ossec/bin/manage_agents -i MDA0I...TRUNCATED_KEY...RiNzI=
```

```
Agent information:
   ID:004
   Name:monitoring-target
   IP Address:10.10.10.10

Confirm adding it?(y/n): y
Added.
```

Then I restart the wazuh agent. But my wazuh-agent has status **never connected**.

I tried both wazuh agent ossec.conf:

```xml
<client>
  <server>
    <address>wazuh-manager.your-domain.com</address>
```
and

```xml
<client>
  <server>
    <address>wazuh-master.your-domain.com</address>
```

***

Sorry for this long post. I hope that from my post we can improve the
wazuh user manual, or add an example.

**Comment by nicop311** [comment]
I tried some modification in the `ossec.conf` configuration file from the Wazuh-agent: but my agent is still in status "nerver_connected".

I am starting to think that it is not possible to use Kubernetes Ingress to expose Wazuh server services. Am I correct with this assumption?

## `ossec.conf` from Wazuh-agent

I try this configuration that customizes ports.

```xml
<ossec_config>
  <client>
    <server>
      <!--Custom Kubernetes Ingress config for enrollement uses port 443 and FQDN instead of port 1514-->
      <address>wazuh-manager.your-domain.com</address>
      <port>443</port>
      <protocol>tcp</protocol>
    </server>
    <config-profile>ubuntu, ubuntu20, ubuntu20.04</config-profile>
    <notify_time>10</notify_time>
    <time-reconnect>60</time-reconnect>
    <auto_restart>yes</auto_restart>
    <crypto_method>aes</crypto_method>

    <!--Custom Kubernetes Ingress config for enrollement uses port 443 and FQDN instead of port 1515-->
    <enrollment>
      <enabled>yes</enabled>
      <manager_address>wazuh-master.your-domain.com</manager_address>
      <port>443</port>
    </enrollment>
  </client>


  <!--Custom Kubernetes Ingress config-->
  <auth>
    <port>443</port> 
  </auth>
  ...
```


## Logs from Wazuh-agent

```
cat /var/ossec/logs/ossec.log
```

```
2021/12/06 17:36:41 wazuh-agentd: INFO: Closing connection to server (wazuh-manager.your-domain.com/10.10.10.2:443/tcp).
2021/12/06 17:36:41 wazuh-agentd: INFO: Trying to connect to server (wazuh-manager.your-domain.com/10.10.10.2:443/tcp).
2021/12/06 17:36:41 wazuh-agentd: ERROR: Corrupt payload (exceeding size) received.
2021/12/06 17:36:51 wazuh-agentd: INFO: Closing connection to server (wazuh-manager.your-domain.com/10.10.10.2:443/tcp).
2021/12/06 17:36:51 wazuh-agentd: INFO: Trying to connect to server (wazuh-manager.your-domain.com/10.10.10.2:443/tcp).
2021/12/06 17:36:51 wazuh-agentd: ERROR: Corrupt payload (exceeding size) received.
2021/12/06 17:36:51 wazuh-agentd: INFO: Requesting a key from server: wazuh-manager.your-domain.com/10.10.10.2
2021/12/06 17:36:51 wazuh-agentd: INFO: No authentication password provided
2021/12/06 17:36:51 wazuh-agentd: INFO: Using agent name as: monitoring-target
2021/12/06 17:36:51 wazuh-agentd: INFO: Waiting for server reply
2021/12/06 17:37:01 wazuh-agentd: WARNING: (4101): Waiting for server reply (not started). Tried: 'wazuh-manager.your-domain.com/10.10.10.2'.
2021/12/06 17:37:01 wazuh-agentd: WARNING: Unable to connect to any server.
2021/12/06 17:37:01 wazuh-agentd: INFO: Closing connection to server (wazuh-manager.your-domain.com/10.10.10.2:443/tcp).
2021/12/06 17:37:01 wazuh-agentd: INFO: Trying to connect to server (wazuh-manager.your-domain.com/10.10.10.2:443/tcp).
2021/12/06 17:37:01 wazuh-agentd: ERROR: Corrupt payload (exceeding size) received.
2021/12/06 17:37:11 wazuh-agentd: INFO: Closing connection to server (wazuh-manager.your-domain.com/10.10.10.2:443/tcp).
2021/12/06 17:37:11 wazuh-agentd: INFO: Trying to connect to server (wazuh-manager.your-domain.com/10.10.10.2:443/tcp).
2021/12/06 17:37:11 wazuh-agentd: ERROR: Corrupt payload (exceeding size) received.
```

**Comment by srinijalagam** [comment]
Hi all,
I am experiencing **wazuh-agentd: ERROR: Corrupt payload (exceeding size) received**  and in dashboard this agent is appearing as never connected , any suggestions?

**Comment by mudasirmirza** [comment]
Hi @nicop311 , did you get this to work. If so, can you please share the steps, would really appreciate it.

**Comment by Cobesz** [comment]
I've managed to get this working, starting with the ingress suggestion from @nicop311.

I'm using the ingress-nginx controller, which can be found here: [ingress-nginx](https://kubernetes.github.io/ingress-nginx/)

The issue, as I understand it, is that the ingress-controller primarily allows for HTTP(S) traffic. However, Wazuh uses plain TCP and implements its own encryption methods.

To resolve this, I opened the required ports on the controller side. Here's how I did it:

## 1. Create or update the ConfigMap for TCP services

I created a ConfigMap in the `ingress-nginx` namespace that maps the TCP ports to the Wazuh services:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: <namespace_that_contains_ingress-nginx>
data:
  1514: "wazuh/wazuh-workers:1514"
  1515: "wazuh/wazuh:1515"
```

I applied the ConfigMap with kubectl apply -f tcp-services.yaml.
## 2. Update the NGINX Ingress Controller deployment

I updated the NGINX Ingress Controller deployment to reference the ConfigMap I just created. The deployment is usually named nginx-ingress-controller and located in the ingress-nginx namespace.

I edited the deployment directly with kubectl edit deployment nginx-ingress-controller -n <namespace_that_contains_ingress-nginx>.

I looked for the args section under spec.template.spec.containers[0] and added --tcp-services-configmap=$(POD_NAMESPACE)/tcp-services to the list of arguments. It should look something like this:

```yaml
spec:
  template:
    spec:
      containers:
        - name: nginx-ingress-controller
          args:
            - /nginx-ingress-controller
            - --configmap=$(POD_NAMESPACE)/nginx-configuration
            - --tcp-services-configmap=$(POD_NAMESPACE)/tcp-services
```

I saved and exited. The deployment automatically updated the running pods.

### 3. Expose the TCP ports on the Ingress Controller
I edited the Ingress Controller service (usually named ingress-nginx-controller in the ingress-nginx namespace) to expose the TCP ports:

```bash
kubectl edit service ingress-nginx-controller -n <namespace_that_holds_ingress-nginx>
```
I added the TCP ports to the ports section under spec:

```yaml
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
### add below ###
    - name: wazuh-manager
      port: 1514
      targetPort: 1514
      protocol: TCP
    - name: wazuh-master
      port: 1515
      targetPort: 1515
      protocol: TCP
```

I saved and exited.

Now, you should be able to connect to the Wazuh manager and Wazuh master services at the domains you specified, on the TCP ports you specified (1514 and 1515, respectively).

Note: 
Please replace `<namespace_that_contains_ingress-nginx>` with the actual namespace that contains your ingress-nginx controller.



For completion, here is the ingress file I used:

```yaml
---
# Dashboard and Wazuh app Web GUI.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wazuh-dashboard-ingress
  namespace: wazuh
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS" # Ensure communication with backend over HTTPS
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - wazuh.my_custom_domain.example
      secretName: wazuh-tls
  rules:
    - host: "wazuh.my_custom_domain.example"
      http:
        paths:
          # Wazuh dashboard
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: dashboard
                port:
                  number: 5601
---
# Wazuh  API
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wazuh-api-ingress
  namespace: wazuh
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS" # Ensure communication with backend over HTTPS
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - wazuh-api.my_custom_domain.example
      secretName: wazuh-api-tls
  rules:
    - host: "wazuh-api.my_custom_domain.example"
      http:
        paths:
          # Wazuh REST API
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: wazuh
                port:
                  number: 55000
---
# Wazuh agent authd registration service.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wazuh-agent-authd-ingress
  namespace: wazuh
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS" # Ensure communication with backend over HTTPS
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - wazuh-master.my_custom_domain.example
      secretName: wazuh-master-tls
  rules:
    - host: "wazuh-master.my_custom_domain.example"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: wazuh
                port:
                  number: 1515
---
# Wazuh Reporting service
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wazuh-reporting-ingress
  namespace: wazuh
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - wazuh-manager.my_custom_domain.example
      secretName: wazuh-manager-tls
  rules:
    - host: "wazuh-manager.my_custom_domain.example"
      http:
        paths:
          # Wazuh Reporting service
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: wazuh-workers
                port:
                  number: 1514
```
