### ISSUE TITLE
Include HTTP_PROXY comment inside docker deployment section

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh-documentation#5218]
Hello team,

After the talk with a community user (stoksoz). We have concluded that deploying wazuh-docker behind an HTTPS proxy can cause some download errors.

So we suggest including a note on this page https://documentation.wazuh.com/current/deployment-options/docker/wazuh-container.html that mentions that you have to include the following block to your compose file to make it works.
```
    environment:
      - HTTP_PROXY=YOUR_PROXY_ADDRESS_OR_DNS
```
Completed file example:
```
# Wazuh App Copyright (C) 2021 Wazuh Inc. (License GPLv2)
version: '3'

services:
  generator:
    image: wazuh/wazuh-certs-generator:0.0.1
    hostname: wazuh-certs-generator
    volumes:
      - ./config/wazuh_indexer_ssl_certs/:/certificates/
      - ./config/certs.yml:/config/certs.yml
    environment:
      - HTTP_PROXY=YOUR_PROXY_ADDRESS_OR_DNS
```
