### ISSUE TITLE
"Happy path" installation steps for "Installing Wazuh with Elastic Stack basic license/Distributed deployment" section not working

### ISSUE THREAD

**Issue by mari0rh** [wazuh/wazuh-documentation#5711]
This configuration requieres only the IP from the **elasticsearch** node. The info is required for the certificates using the elasticsearch-certutil tool. That being said, the certificate will be attached only that specific IP. 

![image](https://user-images.githubusercontent.com/5872740/198279299-82b43ef7-f9d0-40b2-9aee-bd8375e92d45.png)

As the certificate was created using only the elasticsearch node IP the certificate will not work properly. The fix for this is using an additional parameter for the elasticsearch-certutil configuration. Something like this:

```
cat > /usr/share/elasticsearch/instances.yml <<\EOF
instances:
- name: "elasticsearch"
  ip:
  - "10.0.0.2"
  dns: #fix here
  - "myelasticsearchnodedns.com"  #fix here
- name: "filebeat"
  ip:
  - "10.0.0.3"
- name: "kibana"
  ip:
  - "10.0.0.4"
EOF
```

technical reference about the fix here [https://www.elastic.co/guide/en/elasticsearch/reference/current/certutil.html#certutil-silent](url)

What I want to say if that if you follow up the instructions step by step, probably you will have an issue with the certificates. I think the right approach is to assume people will install [The Kibana suggested version ](https://documentation.wazuh.com/current/deployment-options/elastic-stack/distributed-deployment/kibana/index.html#kibana-installation-and-configuration) defined by Wazuh team, and then if they are using a previous version, the cert will work with no problem using the same steps they already made.
