### ISSUE TITLE
Misconfiguration in the default API example

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh-documentation#5800]
## Description

After performing E2E UX testing of the `Wazuh Puppet deployment` for the `v4.4.0` release (https://github.com/wazuh/wazuh/issues/15538), a bug has been found in the configuration example that appears at the beginning of "[Configuration - RESTful API](https://documentation-dev.wazuh.com/v4.4.0-alpha1/user-manual/api/configuration.html#wazuh-api-configuration)".

Apparently, the configuration example has not been modified in the PR corresponding to development https://github.com/wazuh/wazuh/pull/14119:
- https://github.com/wazuh/wazuh-documentation/pull/5417

So it is necessary to fix it to avoid confusion and problems in the API configuration, as has happened in https://github.com/wazuh/wazuh-puppet/issues/611.

The new block would look like the following:
```yaml
# Uploadable Wazuh configuration sections
upload_configuration:
  remote_commands:
    localfile:
      allow: yes
      exceptions: []
    wodle_command:
      allow: yes
      exceptions: []
  limits:
    eps:
      allow: yes
```
