### ISSUE TITLE
Deployment with Ansible fails with current playbook from documentation

### ISSUE THREAD

**Issue by kujo-jotaro** [wazuh/wazuh-documentation#5801]
As of now, the section [Preparing to run the playbook](https://documentation-dev.wazuh.com/4.4/deployment-options/deploying-with-ansible/guide/install-indexer-dashboard.html#preparing-to-run-the-playbook) of the article "Deployment with Ansible" presents a playbook which fails when running it. This is due to a recent change in `wazuh-certs-tool.sh`, where it is verified that at least one indexer node, one dashboard node, and one manager node are specified. If not, the script fails, and subsequently, the playbook does too.

For example:

```console
[root@ansible playbooks]# ansible-playbook wazuh-indexer-and-dashboard.yml -b -K
BECOME password:

PLAY [all_in_one] ***************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************
ok: [192.168.0.145]

TASK [../roles/wazuh/wazuh-indexer : include_vars] ******************************************************************************************************************************************************************************************
ok: [192.168.0.145]

TASK [../roles/wazuh/wazuh-indexer : include_vars] ******************************************************************************************************************************************************************************************
ok: [192.168.0.145]

TASK [../roles/wazuh/wazuh-indexer : include_vars] ******************************************************************************************************************************************************************************************
skipping: [192.168.0.145]

TASK [../roles/wazuh/wazuh-indexer : include_vars] ******************************************************************************************************************************************************************************************
skipping: [192.168.0.145]

TASK [../roles/wazuh/wazuh-indexer : Check if certificates already exists] ******************************************************************************************************************************************************************
ok: [192.168.0.145 -> localhost]

TASK [../roles/wazuh/wazuh-indexer : Local action | Create local temporary directory for certificates generation] ***************************************************************************************************************************
changed: [192.168.0.145 -> localhost]

TASK [../roles/wazuh/wazuh-indexer : Local action | Download certificates generation tool] **************************************************************************************************************************************************
changed: [192.168.0.145 -> localhost]

TASK [../roles/wazuh/wazuh-indexer : Local action | Prepare the certificates generation template file] **************************************************************************************************************************************
changed: [192.168.0.145 -> localhost]

TASK [../roles/wazuh/wazuh-indexer : Local action | Generate the node & admin certificates in local] ****************************************************************************************************************************************
fatal: [192.168.0.145 -> localhost]: FAILED! => {"changed": true, "cmd": ["bash", "/etc/ansible/roles/wazuh-ansible/playbooks/indexer/certificates/wazuh-certs-tool.sh", "-A"], "delta": "0:00:00.168982", "end": "2022-12-02 16:51:46.297039", "msg": "non-zero return code", "rc": 1, "start": "2022-12-02 16:51:46.128057", "stderr": "", "stderr_lines": [], "stdout": "02/12/2022 16:51:46 ERROR: You must specify at least one indexer, one server and one dashboard node.", "stdout_lines": ["02/12/2022 16:51:46 ERROR: You must specify at least one indexer, one server and one dashboard node."]}

NO MORE HOSTS LEFT **************************************************************************************************************************************************************************************************************************

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
192.168.0.145              : ok=8    changed=3    unreachable=0    failed=1    skipped=2    rescued=0    ignored=0
```

It is imperative that this is changed accordingly. Take for example:

```
- hosts: all_in_one
  roles:
    - role: ../roles/wazuh/wazuh-indexer
      perform_installation: false
  become: no
  vars:
    indexer_node_master: true
    instances:
      node1:
        name: node-1
        ip: XXX.XXX.XXX.XXX
        role: indexer
      dashboard:
        name: dashboard
        ip: YYY.YYY.YYY.YYY
        role: dashboard
      manager:
        name: manager
        ip: ZZZ.ZZZ.ZZZ.ZZZ
        role: wazuh
  tags:
    - generate-certs

- hosts: all_in_one
  become: yes
  become_user: root
  roles:
    - role: ../roles/wazuh/wazuh-indexer
    - role: ../roles/wazuh/wazuh-dashboard

  vars:
    single_node: true
    indexer_network_host: 127.0.0.1
    ansible_shell_allow_world_readable_temp: true
    instances:
      node1:
        name: node-1
        ip: 127.0.0.1
        role: indexer
```
