### ISSUE TITLE
Lack of indentation in Wazuh Dashboard configuration file

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh-documentation#5978]
Doing a Wazuh Dashboard configuration for distributed deployments, I could realize there is a lack of indentation in the example:

![image](https://user-images.githubusercontent.com/125690423/226906542-53cdc99a-c40a-4f22-bba2-9f907059edb6.png)

The correct configuration would be:

```
hosts:
  - default:
        url: https://localhost
        port: 55000
        username: wazuh-wui
        password: wazuh-wui
        run_as: false
```

>Note: this mistake faced me spend several minutes to find the error and fix it. Any user would have the same problem.
