### ISSUE TITLE
Add `run_as` option to Wazuh dashboard configuration section on Single Sign documentation

### ISSUE THREAD

**Issue by ace-109** [wazuh/wazuh-documentation#6175]
The `run_as` value needs to be set to `false` in the `/usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml` configuration file. Leaving it as `true`  will show Zero connected agents. The  `/usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml` file should look like this

``` 
hosts:
  - default:
      url: https://localhost
      port: 55000
      username: wazuh-wui
      password: "6TMbkZhBR5nP4W?eJVe1aWTtC.qJPDmw"
      run_as: false
```

This step should be added to the Wazuh dashboard configuration section on [Single Sign documentation](https://documentation.wazuh.com/current/user-manual/user-administration/single-sign-on/okta.html#wazuh-dashboard-configuration)
