### ISSUE TITLE
Add notes about Wazuh reaching the limit for file descriptors in Docker

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh-documentation#6282]
## Description

When following the development documentation on [how to deploy Wazuh using Docker](https://documentation-dev.wazuh.com/v4.5.0-alpha1/deployment-options/docker/wazuh-container.html), I can see some errors in the Wazuh Manager container:

```shell
# sudo docker exec -it single-node-wazuh.manager-1 cat /var/ossec/logs/ossec.log | grep -i -E "error|warn"

2023/07/26 18:34:52 wazuh-db: ERROR: Could not set resource limit for file descriptors to 458752: Operation not permitted (1)
2023/07/26 18:34:54 wazuh-analysisd: ERROR: Could not set resource limit for file descriptors to 458752: Operation not permitted (1)
2023/07/26 18:34:56 wazuh-remoted: ERROR: Could not set resource limit for file descriptors to 458752: Operation not permitted (1)
2023/07/26 18:34:58 wazuh-modulesd: WARNING: 'update_from_year' option cannot be used for 'nvd' provider.
```

I asked the Core team and they mentioned that these kinds of errors are common because of the nature of the Docker environment, which means that some processes in Wazuh (wazuh-db, wazuh-analysisd, wazuh-remoted and wazuh-logcollector) cannot extend their limits of open files because they do not have enough permissions to do so.

## Steps to reproduce

⚠️ Before executing the following steps, make sure you prepared the environment by following [this documentation](https://documentation.wazuh.com/current/deployment-options/docker/docker-installation.html#docker-installation).

| OS | AMI | AWS instance |
|--|--|--
| Amazon Linux 2 (x86_64) | ami-0f9ce67dcf718d332 | c5a.xlarge

I reproduce the bug by following the steps described in [Wazuh Docker deployment](https://documentation.wazuh.com/current/deployment-options/docker/wazuh-container.html#wazuh-docker-deployment):

<details><summary>Steps 🐛</summary><br>

1. Clone the `wazuh-docker` repository
```shell
# git clone https://github.com/wazuh/wazuh-docker.git -b v4.4.5
```
2. Get into the `single-node` folder
```shell
# cd wazuh-docker/single-node
```
3. Generate certificates
```
# sudo docker-compose -f generate-indexer-certs.yml run --rm generator
[+] Running 1/0
 ⠿ Network single-node_default  Created                                                                                                   0.0s
[+] Running 5/5
 ⠿ generator Pulled                                                                                                                       1.7s
   ⠿ d7bfe07ed847 Pull complete                                                                                                           1.0s
   ⠿ a6023cfa8265 Pull complete                                                                                                           1.4s
   ⠿ 6135753eefe9 Pull complete                                                                                                           1.5s
   ⠿ 9aaf0dae5d3f Pull complete                                                                                                           1.5s
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 26847  100 26847    0     0  2016k      0 --:--:-- --:--:-- --:--:-- 2016k
Cert tool exists in Packages bucket
26/07/2023 18:00:47 INFO: Admin certificates created.
26/07/2023 18:00:48 INFO: Wazuh indexer certificates created.
26/07/2023 18:00:48 INFO: Wazuh server certificates created.
26/07/2023 18:00:48 INFO: Wazuh dashboard certificates created.
Moving created certificates to destination directory
changing certificate permissions
Setting UID indexer and dashboard
Setting UID for wazuh manager and worker


# sudo ls -l config/wazuh_indexer_ssl_certs/

total 48
-r-------- 1 ec2-user ec2-user 1704 Jul 26 18:00 admin-key.pem
-r-------- 1 ec2-user ec2-user 1119 Jul 26 18:00 admin.pem
-r-------- 1      101      101 1704 Jul 26 18:00 root-ca-manager.key
-r-------- 1      101      101 1204 Jul 26 18:00 root-ca-manager.pem
-r-------- 1 ec2-user ec2-user 1704 Jul 26 18:00 root-ca.key
-r-------- 1 ec2-user ec2-user 1204 Jul 26 18:00 root-ca.pem
-r-------- 1 ec2-user ec2-user 1704 Jul 26 18:00 wazuh.dashboard-key.pem
-r-------- 1 ec2-user ec2-user 1261 Jul 26 18:00 wazuh.dashboard.pem
-r-------- 1 ec2-user ec2-user 1704 Jul 26 18:00 wazuh.indexer-key.pem
-r-------- 1 ec2-user ec2-user 1257 Jul 26 18:00 wazuh.indexer.pem
-r-------- 1      101      101 1704 Jul 26 18:00 wazuh.manager-key.pem
-r-------- 1      101      101 1257 Jul 26 18:00 wazuh.manager.pem
```

4. Start the Wazuh single-node deployment using docker-compose:
```shell
# docker-compose up -d
```
5. Check for errors/warnings in Wazuh Dashboard
```shell
# sudo docker exec -it single-node-wazuh.dashboard-1 bash

wazuh-dashboard@wazuh:~$ cat /usr/share/wazuh-dashboard/data/wazuh/logs/wazuhapp.log | grep -i -E "error|warn"
{"date":"2023-07-26T18:34:57.464Z","level":"error","location":"monitoring:getApiInfo","message":"connect ECONNREFUSED 172.18.0.3:55000"}
```
> **Note:** This message was shown at startup and it is normal because the Wazuh API was being started.
6. Check for errors/warnings in Wazuh Indexer
```shell
# sudo docker exec -it single-node-wazuh.indexer-1 bash

wazuh-indexer@wazuh:~$ cat /var/log/wazuh-indexer/opensearch.log | grep -i -E "error|warn"
.
.
[2023-07-26T18:34:53,799][ERROR][o.o.s.a.BackendRegistry  ] [wazuh.indexer] Not yet initialized (you may need to run securityadmin)
```
6. Check for errors/warnings in Wazuh Manager 🔴🐛🐛🐛
```shell
# sudo docker exec -it single-node-wazuh.manager-1 bash

root@wazuh:/# cat /var/ossec/logs/ossec.log | grep -i -E "error|warn"
.
.
2023/07/26 18:34:52 wazuh-db: ERROR: Could not set resource limit for file descriptors to 458752: Operation not permitted (1)
2023/07/26 18:34:54 wazuh-analysisd: ERROR: Could not set resource limit for file descriptors to 458752: Operation not permitted (1)
2023/07/26 18:34:56 wazuh-remoted: ERROR: Could not set resource limit for file descriptors to 458752: Operation not permitted (1)
2023/07/26 18:34:58 wazuh-modulesd: WARNING: 'update_from_year' option cannot be used for 'nvd' provider.
```
> **Note:** WARNING messages are expected (ref: https://github.com/wazuh/wazuh-docker/issues/909).

</details>

## Expected results

- A note clarifying that this is an expected error in the guide of Deployment on Docker
- A note with a workaround to allow the processes to expand their limits of open files (I suggest that @wazuh/core make a proposal of this workaround)

## Current results

- The user can't really tell if it's just a common error or something related to the environment. It kinda gives the impression of a malfunctioning Wazuh (which isn't true though).

**Comment by vcerenu** [comment]
The error is related to the file limits, so it is proposed to expand the amount of this parameter in the Wazuh Docker deployment::

``` yaml
wazuh.manager:
    image: wazuh/wazuh-manager:4.5.0
    hostname: wazuh.manager
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 655360
        hard: 655360
    ports:
      - "1514:1514"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    environment:
      - INDEXER_URL=https://wazuh.indexer:9200
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=SecretPassword
      - FILEBEAT_SSL_VERIFICATION_MODE=full
      - SSL_CERTIFICATE_AUTHORITIES=/etc/ssl/root-ca.pem
      - SSL_CERTIFICATE=/etc/ssl/filebeat.pem
      - SSL_KEY=/etc/ssl/filebeat.key
      - API_USERNAME=wazuh-wui
      - API_PASSWORD=MyS3cr37P450r.*-
    volumes:
      - wazuh_api_configuration:/var/ossec/api/configuration
      - wazuh_etc:/var/ossec/etc
      - wazuh_logs:/var/ossec/logs
      - wazuh_queue:/var/ossec/queue
      - wazuh_var_multigroups:/var/ossec/var/multigroups
      - wazuh_integrations:/var/ossec/integrations
      - wazuh_active_response:/var/ossec/active-response/bin
      - wazuh_agentless:/var/ossec/agentless
      - wazuh_wodles:/var/ossec/wodles
      - filebeat_etc:/etc/filebeat
      - filebeat_var:/var/lib/filebeat
      - ./config/wazuh_indexer_ssl_certs/root-ca-manager.pem:/etc/ssl/root-ca.pem
      - ./config/wazuh_indexer_ssl_certs/wazuh.manager.pem:/etc/ssl/filebeat.pem
      - ./config/wazuh_indexer_ssl_certs/wazuh.manager-key.pem:/etc/ssl/filebeat.key
      - ./config/wazuh_cluster/wazuh_manager.conf:/wazuh-config-mount/etc/ossec.conf
```

Tests were carried out on the same environment on which the errors were taken and the same ones were no longer generated.
