### ISSUE TITLE
Outdated reference for the Wazuh certificate image in the Wazuh docker deployment

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-documentation#7512]
# Description

The current Wazuh certificate generator image for the 4.8.0 version is [0.0.2](https://github.com/wazuh/wazuh-docker/blob/v4.8.0/single-node/generate-indexer-certs.yml#L6), not 0.0.1, we need to update the documentation or remove that reference as that specific part is about the proxy configuration.

- https://documentation.wazuh.com/current/deployment-options/docker/wazuh-container.html#single-node-deployment
- https://documentation.wazuh.com/current/deployment-options/docker/wazuh-container.html#multi-node-deployment

```
services:
  generator:
    image: wazuh/wazuh-certs-generator:0.0.1
    hostname: wazuh-certs-generator
    volumes:
      - ./config/wazuh_indexer_ssl_certs/:/certificates/
      - ./config/certs.yml:/config/certs.yml
    environment:
      - HTTP_PROXY=YOUR_PROXY_ADDRESS_OR_DNS
```
